server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#configuration for congig server
  config:
    import: optional:configserver:http://localhost:8085
    
 #security configuration   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-40631588.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oagrr3x18AQtO8wp5d7
            client-secret: 783B4nXCbBQwpXiVhFQWjMukHpUAUDSaXJ01LVbTFLxGyK89IJqV4zck6t0chet3

        provider:
          okta:
            issuer-uri: https://dev-40631588.okta.com/oauth2/default
# jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#circuit breaker configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health        
  endpoint:
    health:
      show-details: always
        
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  #implement retry module      
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
               
  #implement rate limiter      
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s   

#okta configuration for api gateway         
okta:
  oauth2:
    issuer: https://dev-40631588.okta.com/oauth2/default
    audience: api://default 
        
        
        
        
        
        
        
        
        
        
        